### ISSUE TITLE
Migration to null safety

### ISSUE THREAD

**Issue by arthurgiani** [lapadev/chat-list-flutter-package#2]
Hi Igor,

Is there a plan to migrate the package to null safety?

Thank you very much!

**Comment by higorlapa** [comment]
Hi, @arthurgiani!

yes, I’m migrating it. I will send the null-safety version in a couple days

**Comment by higorlapa** [comment]
@arthurgiani, done!

**Comment by arthurgiani** [comment]
> @arthurgiani, done!

thank you very much!
